name: Build SlashBack

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Automatically install Gradle if gradlew is missing
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew clean build --no-daemon
          else
            gradle clean build --no-daemon
          fi

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SlashBack-artifacts
          path: build/libs/*.jar

      - name: Run tests (if applicable)
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew test --no-daemon
          else
            gradle test --no-daemon
          fi
