name: Build SlashBack

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Set up Gradle 5.6.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 5.6.4

      - name: Build with Gradle
        run: gradle clean build --no-daemon

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SlashBack-artifacts
          path: build/libs/*.jar
